name: beesiha_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.4
  fluttertoast: ^8.0.8
  animated_widgets: ^1.1.0
  animations: ^2.0.2
  after_layout: ^1.1.0
  hive: ^2.0.4
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  path_provider: ^2.0.2
  eva_icons_flutter: ^3.0.2
  animated_text_kit: ^4.2.1
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.1.5
  auto_route: ^5.0.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  flutter_bloc: ^8.0.1
  flutter_animate: ^2.0.1
  tuple: ^2.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  retrofit: ^3.3.1
  get_it: ^7.2.0
  injectable: ^1.5.4
  shimmer: ^2.0.0
  provider: ^6.0.5
  url_launcher: ^6.0.15
  streaming_shared_preferences: ^2.0.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  firebase_auth: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.0.3
  retrofit_generator: ^4.2.0
  injectable_generator: ^1.5.5

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
